### ISSUE TITLE
Unable to create HTML 5 template

### ISSUE THREAD

**Issue by Animeshz** [lukasjapan/koreander#9]
# 1. Reproducable example:
  * Create main.kt and put following code:
    ```kotlin
    fun main() {
        val kor = javaClass.getResource("/index.kor").readText()
        Koreander().render(kor, Any())
    }
    ```
  * Create index.kor in resource directory in `src/main` folder of project and put the following code:
    ```kor
    !!! 5
    %html
        %head
        %body
            %p.hello Hello World!
    ```

# 2. Expected result:
Expected to see the `<!DOCTYPE html>` declaration instead of the exception.

# 3. Actual result:
`de.cvguy.kotlin.koreander.exception.UnexpectedDocType: Parse error in tba at 0:4 - Unexpexted DocType 5` exception thrown

# 4. StackTrace:
```
de.cvguy.kotlin.koreander.exception.UnexpectedDocType: Parse error in tba at 0:4 - Unexpexted DocType 5
	at de.cvguy.kotlin.koreander.parser.KoreanderParseEngine.unshiftDocType(Parser.kt:169)
	at de.cvguy.kotlin.koreander.parser.KoreanderParseEngine.parse(Parser.kt:79)
	at de.cvguy.kotlin.koreander.parser.KoreanderParser.generateScriptCode(Parser.kt:17)
	at de.cvguy.kotlin.koreander.Koreander.compile(Koreander.kt:81)
	at com.github.animeshz.konvironment.http.RoutingKt$module$1$1.invokeSuspend(Routing.kt:27)
	at com.github.animeshz.konvironment.http.RoutingKt$module$1$1.invoke(Routing.kt)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(PipelineContext.kt:273)
	at io.ktor.util.pipeline.SuspendFunctionGun.proceed(PipelineContext.kt:141)
	at io.ktor.util.pipeline.SuspendFunctionGun.execute(PipelineContext.kt:161)
	at io.ktor.util.pipeline.Pipeline.execute(Pipeline.kt:27)
	at io.ktor.routing.Routing.executeResult(Routing.kt:147)
	at io.ktor.routing.Routing.interceptor(Routing.kt:34)
	at io.ktor.routing.Routing$Feature$install$1.invokeSuspend(Routing.kt:99)
	at io.ktor.routing.Routing$Feature$install$1.invoke(Routing.kt)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(PipelineContext.kt:273)
	at io.ktor.util.pipeline.SuspendFunctionGun.proceed(PipelineContext.kt:141)
	at io.ktor.util.pipeline.SuspendFunctionGun.execute(PipelineContext.kt:161)
	at io.ktor.util.pipeline.Pipeline.execute(Pipeline.kt:27)
	at io.ktor.server.engine.DefaultEnginePipelineKt$defaultEnginePipeline$2.invokeSuspend(DefaultEnginePipeline.kt:118)
	at io.ktor.server.engine.DefaultEnginePipelineKt$defaultEnginePipeline$2.invoke(DefaultEnginePipeline.kt)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(PipelineContext.kt:273)
	at io.ktor.util.pipeline.SuspendFunctionGun.proceed(PipelineContext.kt:141)
	at io.ktor.util.pipeline.SuspendFunctionGun.execute(PipelineContext.kt:161)
	at io.ktor.util.pipeline.Pipeline.execute(Pipeline.kt:27)
	at io.ktor.server.netty.NettyApplicationCallHandler$handleRequest$1.invokeSuspend(NettyApplicationCallHandler.kt:40)
	at io.ktor.server.netty.NettyApplicationCallHandler$handleRequest$1.invoke(NettyApplicationCallHandler.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startCoroutineUndispatched(Undispatched.kt:55)
	at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:111)
	at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:158)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:54)
	at kotlinx.coroutines.BuildersKt.launch(Unknown Source)
	at io.ktor.server.netty.NettyApplicationCallHandler.handleRequest(NettyApplicationCallHandler.kt:30)
	at io.ktor.server.netty.NettyApplicationCallHandler.channelRead(NettyApplicationCallHandler.kt:24)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.access$600(AbstractChannelHandlerContext.java:56)
	at io.netty.channel.AbstractChannelHandlerContext$7.run(AbstractChannelHandlerContext.java:365)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:510)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:518)
	at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1050)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)

```

**Comment by lukasjapan** [comment]
Hmm, I think I messed up some whitespace handling.. Will fix this during the weekend.

**Comment by Animeshz** [comment]
**PS:** Well the template written in the runtime actually works idk how.
```kotlin
println(Koreander().render("""
    |!!! 5
    |%html
    |    %head
    |    %body
    |        %p.hello Hello World!
""".trimMargin(), Any()))
```
this actually do render the `<!DOCTYPE html>` without any exception.

Probably there's some problem with parsing the resource,

**Comment by lukasjapan** [comment]
I just reproduced the issue.

Your file probably has windows linefeeds (`\r\n`) which causes the problem.

The Parser parses the doctype as `5\r` and then comparison fails. The error message is confusing because it does not show the additional `\r`.

**Comment by Animeshz** [comment]
For the debugging, I've created a small script so that you can figure out the main cause easily:

### Script
```kotlin
fun main()  {
    val fromString =
        """
        |!!! 5
        |%html
        |    %head
        |    %body
        |        %p.hello Hello World!
        |""".trimMargin()

    val fromResource = Unit.javaClass.getResource("/index.kor").readText()

    println("fromString:")
    println(fromString)
    println()
    println("fromResource: ")
    println(fromResource)
    println()


    val lexFromString = Lexer().lexString(fromString)

    val lexFromResource = Lexer().lexString(fromResource)

    println("lexFromString: ")
    println(lexFromString.joinToString("\n"))
    println()

    println("lexFomResource: ")
    println(lexFromResource.joinToString("\n"))
    println()
}
```
### Result:
```
fromString:
!!! 5
%html
    %head
    %body
        %p.hello Hello World!


fromResource: 
!!! 5
%html
    %head
    %body
        %p.hello Hello World!

lexFromString: 
Token(type=DOC_TYPE_IDENTIFIER, content=!!!, line=0, character=0, offset=0)
Token(type=DOC_TYPE, content=5, line=0, character=4, offset=4)
Token(type=WHITE_SPACE, content=, line=0, character=5, offset=5)
Token(type=WHITE_SPACE, content=, line=1, character=0, offset=6)
Token(type=ELEMENT_IDENTIFIER, content=%, line=1, character=0, offset=6)
Token(type=STRING, content=html, line=1, character=1, offset=7)
Token(type=WHITE_SPACE, content=    , line=2, character=0, offset=12)
Token(type=ELEMENT_IDENTIFIER, content=%, line=2, character=4, offset=16)
Token(type=STRING, content=head, line=2, character=5, offset=17)
Token(type=WHITE_SPACE, content=    , line=3, character=0, offset=22)
Token(type=ELEMENT_IDENTIFIER, content=%, line=3, character=4, offset=26)
Token(type=STRING, content=body, line=3, character=5, offset=27)
Token(type=WHITE_SPACE, content=        , line=4, character=0, offset=32)
Token(type=ELEMENT_IDENTIFIER, content=%, line=4, character=8, offset=40)
Token(type=STRING, content=p, line=4, character=9, offset=41)
Token(type=ELEMENT_CLASS_IDENTIFIER, content=., line=4, character=10, offset=42)
Token(type=STRING, content=hello, line=4, character=11, offset=43)
Token(type=TEXT, content=Hello World!, line=4, character=17, offset=49)
Token(type=WHITE_SPACE, content=, line=5, character=0, offset=62)

lexFomResource: 
Token(type=DOC_TYPE_IDENTIFIER, content=!!!, line=0, character=0, offset=0)
, line=0, character=4, offset=4)
Token(type=WHITE_SPACE, content=, line=0, character=6, offset=6)
Token(type=WHITE_SPACE, content=, line=1, character=0, offset=7)
Token(type=ELEMENT_IDENTIFIER, content=%, line=1, character=0, offset=7)
, line=1, character=1, offset=8)
Token(type=WHITE_SPACE, content=    , line=2, character=0, offset=14)
Token(type=ELEMENT_IDENTIFIER, content=%, line=2, character=4, offset=18)
, line=2, character=5, offset=19)
Token(type=WHITE_SPACE, content=    , line=3, character=0, offset=25)
Token(type=ELEMENT_IDENTIFIER, content=%, line=3, character=4, offset=29)
, line=3, character=5, offset=30)
Token(type=WHITE_SPACE, content=        , line=4, character=0, offset=36)
Token(type=ELEMENT_IDENTIFIER, content=%, line=4, character=8, offset=44)
Token(type=STRING, content=p, line=4, character=9, offset=45)
Token(type=ELEMENT_CLASS_IDENTIFIER, content=., line=4, character=10, offset=46)
Token(type=STRING, content=hello, line=4, character=11, offset=47)
Token(type=TEXT, content=Hello World!, line=4, character=17, offset=53)
```

**Comment by Animeshz** [comment]
You were right, adding this solves the issue:
```kotlin
val fromResource = Unit.javaClass
    .getResource("/templates/index.kor")
    .readText()
    .replace(System.getProperty("line.separator"), "\n")
```
Default line seperator should be replaced by this. I'm closing the issue. If required please do check/use `String.replace(System.getProperty("line.separator"), "\n")` before doing any operation in the `Lexer.lexString()` function to support the windows system in your library!

**Comment by lukasjapan** [comment]
I added support for quirky windows file format in the latest version. (`0.1.0`)

-> remove BOM
-> support `\r\n`

https://github.com/lukasjapan/koreander/commit/4c9fb6efa7436454865d3f7656a4e033c1ec5347
